variables:
  COMPOSE_FILE: ./containers/docker-compose-testing.yml

before_script:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose run web bundle install
  - docker-compose up -d
  - docker-compose exec web sleep 5
  - docker-compose exec web bash -c "rake db:setup"
  - docker-compose exec web bash -c "rake db:migrate"
  - docker-compose exec web bower install --allow-root

job:
  image: docker/compose
  script:
    - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rake test:all"
    - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rails test -d"
    - echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml
    - tail -n +2 -q ./test/reports/TEST*.xml >> output.xml
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi'
